import { Project, ServiceDetail, ProcessStep, Testimonial, BlogPost } from './types';

// Let's use the exact image paths generated by the tool
export const IMAGES = {
  portrait: '/src/assets/images/nirmal_kaushik_portrait_1783329645716.jpg',
  villa: '/src/assets/images/portfolio_villa_1783329660319.jpg',
  interior: '/src/assets/images/portfolio_interior_1783329675650.jpg',
  commercial: '/src/assets/images/portfolio_commercial_1783329691905.jpg',
  defaultHero: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1920&q=80',
  architecturalSketch: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80',
};

export const SERVICES: Record<string, ServiceDetail> = {
  architecture: {
    title: 'Architecture',
    description: 'We design bespoke architectural masterpieces that seamlessly combine spatial efficiency, technical precision, and modern aesthetics to shape the built environment.',
    items: [
      'Residential Architecture',
      'Luxury Villas & Farmhouses',
      'Apartments & Group Housing',
      'Commercial Buildings',
      'Office Spaces',
      'Institutional Buildings',
      'Healthcare Facilities',
      'Hospitality Projects',
      'Industrial Buildings',
      'Mixed-Use Developments'
    ]
  },
  interior: {
    title: 'Interior Design',
    description: 'Transforming interior spaces into functional, highly elegant, and immersive environments tailored to the lifestyles and corporate identities of our clients.',
    items: [
      'Residential Interiors',
      'Commercial Interiors',
      'Office Interiors',
      'Retail & Showroom Design',
      'Restaurant & Café Design',
      'Hotel & Hospitality Interiors',
      'Custom Furniture Design'
    ]
  },
  planning: {
    title: 'Planning & Consultancy',
    description: 'Providing comprehensive master planning, landscape integration, and detailed documentation from initial feasibility research through complete site execution.',
    items: [
      'Master Planning',
      'Urban Design',
      'Landscape Design',
      'Site Planning',
      'Building Renovation',
      'Adaptive Reuse',
      'Project Consultancy',
      'Construction Documentation',
      'Municipal Approval Drawings',
      'Site Supervision'
    ]
  },
  digital: {
    title: 'Digital Design',
    description: 'Using state-of-the-art visual computing technologies to present architectural concepts through photo-realistic renderings and immersive animations.',
    items: [
      '3D Architectural Visualization',
      'Walkthrough Animation',
      'BIM Modeling',
      'Presentation Drawings'
    ]
  }
};

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: '01',
    title: 'Consultation',
    description: 'Understanding your vision, lifestyle, budget, and project requirements through extensive initial meetings.',
    iconName: 'MessageSquare'
  },
  {
    number: '02',
    title: 'Concept Design',
    description: 'Developing creative spatial ideas, hand-drawn sketch diagrams, and initial layout options.',
    iconName: 'Compass'
  },
  {
    number: '03',
    title: 'Design Development',
    description: 'Preparing detailed structural plans, high-fidelity 3D visualizations, and curated interior material selections.',
    iconName: 'Layers'
  },
  {
    number: '04',
    title: 'Construction Documentation',
    description: 'Creating precise technical working drawings and architectural specifications for field execution.',
    iconName: 'FileText'
  },
  {
    number: '05',
    title: 'Project Execution',
    description: 'Coordinating with engineering consultants and verified contractors to guarantee absolute structural quality.',
    iconName: 'Hammer'
  },
  {
    number: '06',
    title: 'Project Completion',
    description: 'Delivering exceptional, breathtaking spaces that exceed expectations and stand the test of time.',
    iconName: 'CheckCircle'
  }
];

export const CORE_VALUES = [
  { title: 'Innovation', desc: 'Pushing design boundaries with pioneering architectural solutions.' },
  { title: 'Integrity', desc: 'Conducting every client engagement with transparency and absolute honesty.' },
  { title: 'Sustainability', desc: 'Integrating energy-efficient systems and eco-friendly structural practices.' },
  { title: 'Quality', desc: 'Uncompromised precision in documentation, material selection, and site construction.' },
  { title: 'Transparency', desc: 'Fostering open workflows, honest budgets, and realistic project timelines.' },
  { title: 'Client Satisfaction', desc: 'Ensuring your spatial aspirations are entirely realized at completion.' },
  { title: 'Creativity', desc: 'Infusing aesthetic brilliance and artistic expression in functional layouts.' },
  { title: 'Professional Excellence', desc: 'Adhering to international standards in every stage of consultancy.' }
];

export const WHY_CHOOSE_US = [
  'Established architectural firm since 2013',
  'Led by Ar. Nirmal Kaushik (M.Arch., B.Arch.)',
  'Innovative and customized design solutions',
  'Sustainable and energy-efficient architecture',
  'Modern planning and visualization techniques',
  'Complete architectural and interior consultancy',
  'Strong technical expertise and attention to detail',
  'Transparent communication and timely project delivery',
  'Dedicated client support from concept to completion'
];

export const PROJECTS: Project[] = [
  {
    id: 'proj-1',
    title: 'The Zenith Villa',
    category: 'Architecture',
    subCategory: 'Luxury Villas & Farmhouses',
    image: IMAGES.villa,
    description: 'A striking modern two-story private sanctuary designed with a brutalist concrete framework juxtaposed against warm, natural timber paneling. Features high floor-to-ceiling glass envelopes, a continuous transition to a manicured garden with a reflective infinity lap pool, and integrated passive solar design for high energy efficiency.',
    location: 'Gurugram, Haryana',
    year: '2022',
    area: '7,500 Sq. Ft.',
    client: 'Private Residence',
    specs: ['Passive Solar Ventilation', 'High-Thermal Concrete Envelope', 'Timber Louvers', 'Rainwater Harvesting System']
  },
  {
    id: 'proj-2',
    title: 'The Serene Penthouse',
    category: 'Interior Design',
    subCategory: 'Residential Interiors',
    image: IMAGES.interior,
    description: 'A modern, high-end residential living room and master suite redesigned to prioritize luxury, visual harmony, and a calming interior landscape. Employs a soft neutral palette of cream and sand tones, matched with customized oak carpentry and hand-finished travertine marble surfaces.',
    location: 'Noida, Uttar Pradesh',
    year: '2023',
    area: '4,200 Sq. Ft.',
    client: 'Kaushik Residence',
    specs: ['Custom Travertine Fireplace', 'Integrated Cove LED Lighting', 'Bespoke Walnut Furniture', 'Acoustic Ceiling Treatment']
  },
  {
    id: 'proj-3',
    title: 'Nexus Corporate Plaza',
    category: 'Architecture',
    subCategory: 'Commercial Buildings & Offices',
    image: IMAGES.commercial,
    description: 'An state-of-the-art commercial headquarters integrating a low-carbon steel core with dynamic vertical gardens. Designed with high performance solar louvers that dynamically minimize solar heat gain while flooding the workspace lobbies with diffused, comfortable natural light.',
    location: 'New Delhi',
    year: '2021',
    area: '45,000 Sq. Ft.',
    client: 'Nexus Developments',
    specs: ['BIM Level 2 Coordination', 'Double-Glazed Low-E Glass', 'Drip-Irrigated Living Walls', 'LEED Gold Certified Framework']
  },
  {
    id: 'proj-4',
    title: 'Apex Academic Center',
    category: 'Planning & Consultancy',
    subCategory: 'Institutional Buildings',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=80',
    description: 'Comprehensive campus master planning and structural design of a multi-disciplinary block. Organized around central courtyard nodes that encourage interaction, natural microclimate cooling, and seamless connectivity to recreational landscape gardens.',
    location: 'Dehradun, Uttarakhand',
    year: '2020',
    area: '120,000 Sq. Ft.',
    client: 'Dehradun Educational Trust',
    specs: ['Microclimate Courtyard Nodes', 'Greywater Treatment Plant', 'Universally Accessible Design', 'Local Stone Cladding']
  },
  {
    id: 'proj-5',
    title: 'The Ritz Wellness Pavilion',
    category: 'Interior Design',
    subCategory: 'Hotel & Hospitality Interiors',
    image: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80',
    description: 'An ultra-luxury wellness retreat and spa utilizing organic textures and natural lighting. Designed with a calming indoor thermal pool, curved plaster walls, and custom linear diffusers that establish a highly sensory, sensory-calming hospitality experience.',
    location: 'Rishikesh, Uttarakhand',
    year: '2024',
    area: '18,000 Sq. Ft.',
    client: 'Ritz Hospitality Group',
    specs: ['Curved Plaster Finishes', 'Thermal Mass Regulation', 'Custom Integrated Acoustic Panels', 'Bespoke Brass Fixtures']
  },
  {
    id: 'proj-6',
    title: 'Nirvana Mixed-Use Enclave',
    category: 'Digital Design',
    subCategory: 'BIM & Walkthrough Animation',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    description: 'A complete virtual digital twin modeling and BIM simulation of a high-density transit-oriented commercial block. Delivered high-fidelity immersive walkthrough animations and fully coordinated structural, electrical, and plumbing blueprints.',
    location: 'Gurugram, Haryana',
    year: '2023',
    area: '250,000 Sq. Ft.',
    client: 'Nirvana Spaces LLC',
    specs: ['BIM Clash Detection', '4D Construction Scheduling Simulation', 'Immersive VR Walkthrough', 'Clash-Free HVAC Routing']
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't-1',
    name: 'Sanjeev Goel',
    role: 'Managing Director, Goel Properties',
    location: 'New Delhi',
    quote: 'Ar. Nirmal Kaushik is an exceptionally talented architect. His firm delivered our commercial plaza on Gurugram Expressway ahead of schedule, with a design that has become a major landmark. His transparency regarding material pricing and meticulous drawings saved us millions in site revisions.',
    rating: 5
  },
  {
    id: 't-2',
    name: 'Anjali Sharma',
    role: 'Homeowner, The Zenith Villa',
    location: 'Gurugram',
    quote: 'Building our dream villa was an emotional journey, and Vishwakarma Creation Architects made it flawless. Ar. Nirmal spent hours understanding how our family lives, resulting in a layout that feels remarkably spacious, naturally bright, and incredibly warm. The modern concrete-timber aesthetics are perfect.',
    rating: 5
  },
  {
    id: 't-3',
    name: 'Dr. Rajiv Mehta',
    role: 'Trustee, Dehradun Educational Trust',
    location: 'Dehradun',
    quote: 'The academic center designed by Nirmal has completely revitalized our campus. The courtyard design utilizes natural draft cooling, which is highly appreciated by students and reduces our summer electrical loads by almost 35%. His team has exceptional technical skills and site supervision.',
    rating: 5
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b-1',
    title: 'The Vernacular & Modern: Integrating Vastu in Contemporary Minimalist Architecture',
    excerpt: 'Explore how Vishwakarma Creation Architects harmoniously blends ancient Vastu Shastra space arrangements with clean modern lines, high-performance glass, and open floor planning.',
    category: 'Design Philosophy',
    date: 'May 15, 2026',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'b-2',
    title: 'Designing for Extreme Indian Summers: Passive Cooling Techniques That Actually Work',
    excerpt: 'An in-depth look at how Ar. Nirmal Kaushik integrates double-skin envelopes, microclimatic courtyards, thermal mass insulation, and sun-shading louvers to reduce HVAC dependence.',
    category: 'Sustainability',
    date: 'June 10, 2026',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'b-3',
    title: 'The Shift to BIM: Redefining Architectural Execution & Precision in 2026',
    excerpt: 'Discover why 3D Building Information Modeling (BIM) is a game-changer for large-scale developments, reducing site coordination errors, material wastage, and ensuring accurate execution.',
    category: 'Technology',
    date: 'June 28, 2026',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?auto=format&fit=crop&w=600&q=80'
  }
];
